### PR TITLE
Better compatibility to field names generated by protoc-gen-go

### PR DESCRIPTION
**Pull request by yugui**
Stop emulating the conversion rule.  Use their implementation of the name conversion instead.

c.f. #85

### CODE REVIEW

**Comment by shurcooL** [comment]
Nice change!

**Comment by achew22** [comment]
Will this have any affect on the field names in the swagger documentation?

**Comment by yugui** [comment]
> Will this have any affect on the field names in the swagger documentation?

I don't think so because swagger generator does not directly use name conversion, and the currently `gogen.CamelCase` and `utilities.PascalFromSnake` are exactly same.

**Comment by achew22** [comment]
LGTM

**Pull request merged**
