### PR TITLE
Better grpc error strings

### PR DESCRIPTION
**Pull request by floridoo**
See issue #87

### CODE REVIEW

**Comment by yugui** [comment]
test failing.

**Comment by floridoo** [comment]
but unrelated to the pull request, it fails on the master branch too

**Comment by sadlil** [comment]
Fails as json.Unmarshal can't unmarshal int into string here. @floridoo 
[errors_test.go](https://github.com/sadlil/grpc-gateway/blob/master/runtime/errors_test.go#L46)

**Comment by floridoo** [comment]
Passing now.

Thanks @sadlil

**Comment by yugui** [comment]
LGTM

**Pull request merged**
